# Generated by Django 5.2.4 on 2025-09-19 00:12

from django.db import migrations


def create_user_profiles(apps, schema_editor):
    """
    Create UserProfile records for all existing users with default values
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('authx', 'UserProfile')

    # Get all users that don't have profiles yet
    users_without_profiles = User.objects.filter(profile__isnull=True)

    profiles_to_create = []
    for user in users_without_profiles:
        profiles_to_create.append(
            UserProfile(
                user=user,
                language='EN',
                unit_system='Imperial',
                preferred_mode='Light'
            )
        )

    # Bulk create all profiles
    if profiles_to_create:
        UserProfile.objects.bulk_create(profiles_to_create)
        print(f"Created {len(profiles_to_create)} UserProfile records for existing users")


def reverse_create_user_profiles(apps, schema_editor):
    """
    Remove all UserProfile records (reverse migration)
    """
    UserProfile = apps.get_model('authx', 'UserProfile')
    UserProfile.objects.all().delete()
    print("Deleted all UserProfile records")


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_user_profiles,
            reverse_create_user_profiles,
        ),
    ]
