# Generated by Django 5.2.4 on 2025-09-18 23:32

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0002_create_profiles_for_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the existing table if it exists
        migrations.RunSQL(
            "DROP TABLE IF EXISTS authx_userprofile;",
            reverse_sql="-- No reverse operation"
        ),

        # Recreate the table with proper MySQL constraints
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='EN', help_text='User language preference (e.g., EN, ES)', max_length=10, db_index=False)),
                ('unit_system', models.CharField(default='Imperial', help_text='Unit system preference (Imperial/Metric)', max_length=20, db_index=False)),
                ('preferred_mode', models.CharField(default='Light', help_text='Theme preference (Light/Dark)', max_length=10, db_index=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, db_index=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'authx_userprofile',
            },
        ),
    ]
