# Generated by Django 5.2.4 on 2025-07-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='page_images/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workspace.workspace')),
            ],
        ),
    ]
