# Generated by Django 5.2.4 on 2025-08-01 00:07

import workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_pageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(upload_to=workspace.models.fullpage_upload_path),
        ),
    ]
