# Generated by Django 5.2.4 on 2025-08-20 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_workspace_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='scale_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='scale_unit',
            field=models.CharField(blank=True, choices=[('in', 'Inch'), ('ft', 'Foot'), ('cm', 'Centimeter'), ('m', 'Meter')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_scale_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_scale_unit',
            field=models.CharField(blank=True, choices=[('in', 'Inch'), ('ft', 'Foot'), ('cm', 'Centimeter'), ('m', 'Meter')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pipeline_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pipeline_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='idle', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='pipeline_step',
            field=models.CharField(choices=[('queued', 'Queued'), ('load_pdf', 'Load PDF'), ('render_pages', 'Render Pages to Images'), ('tile_pages', 'Divide Pages into Tiles'), ('extract_polygons', 'Extract Polygons'), ('postprocess', 'Postprocess/Index'), ('finished', 'Finished')], db_index=True, default='queued', max_length=32),
        ),
        migrations.AddField(
            model_name='workspace',
            name='project_status',
            field=models.CharField(choices=[('incomplete_setup', 'Incomplete Setup'), ('scaling_pending', 'Scaling Pending'), ('scaled_partial', 'Scaled (Partial)'), ('ready', 'Ready')], db_index=True, default='incomplete_setup', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='soft_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='page_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='pageimage',
            unique_together={('workspace', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='pageimage',
            index=models.Index(fields=['workspace', 'page_number'], name='workspace_p_workspa_5cefdd_idx'),
        ),
        migrations.AddIndex(
            model_name='pageimage',
            index=models.Index(fields=['workspace', 'scale_ratio', 'scale_unit'], name='workspace_p_workspa_2705a8_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['soft_deleted', 'created_at'], name='workspace_w_soft_de_9a4b33_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['user', 'soft_deleted', 'created_at'], name='workspace_w_user_id_1b9cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['pipeline_state', 'pipeline_step'], name='workspace_w_pipelin_69b371_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['project_status', 'soft_deleted'], name='workspace_w_project_909bb7_idx'),
        ),
    ]
