# Generated by Django 5.2.4 on 2025-08-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_pageimage_scale_ratio_pageimage_scale_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='scale_unit',
            field=models.CharField(blank=True, choices=[('in', 'Inch'), ('ft', 'Foot'), ('cm', 'Centimeter'), ('mm', 'Milimeter'), ('m', 'Meter')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='default_scale_unit',
            field=models.CharField(blank=True, choices=[('in', 'Inch'), ('ft', 'Foot'), ('cm', 'Centimeter'), ('mm', 'Milimeter'), ('m', 'Meter')], max_length=8, null=True),
        ),
    ]
