# Generated by Django 5.2.4 on 2025-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_pageimage_scale_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
