# Generated by Django 5.2.4 on 2025-08-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_pageimage_synced_at_pageimage_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='sync_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='sync_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
