# Generated by Django 5.2.4 on 2025-08-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_pageimage_sync_id_workspace_sync_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], db_index=True, default='pending', max_length=16),
        ),
    ]
