# Generated by Django 5.2.4 on 2025-08-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_workspace_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='scale_bar_crop_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='scale_bar_line_coords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='scale_units_per_px',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='scale_unit',
            field=models.CharField(blank=True, choices=[('in', 'Inch'), ('ft', 'Foot'), ('cm', 'Centimeter'), ('mm', 'Milimeter'), ('m', 'Meter'), ('yd', 'Yard')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='default_scale_unit',
            field=models.CharField(blank=True, choices=[('in', 'Inch'), ('ft', 'Foot'), ('cm', 'Centimeter'), ('mm', 'Milimeter'), ('m', 'Meter'), ('yd', 'Yard')], max_length=8, null=True),
        ),
    ]
