# Generated by Django 5.2.4 on 2025-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_pageimage_scale_bar_crop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='auto_extract_on_upload',
            field=models.BooleanField(default=False),
        ),
    ]
