# Generated by Django 5.2.4 on 2025-09-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_workspace_auto_extract_on_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='analyze_region',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='dpi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='extract_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success'), ('canceled', 'Canceled')], db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='segmentation_choice',
            field=models.CharField(choices=[('generic', 'Generic'), ('contoured', 'Contoured')], db_index=True, default='generic', max_length=16),
        ),
    ]
