# Generated by Django 5.2.4 on 2025-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_pageimage_analyze_region_pageimage_dpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='extract_status',
            field=models.CharField(choices=[('none', 'None'), ('queued', 'Queued'), ('processing', 'Processing'), ('failed', 'Failed'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, default='none', max_length=16),
        ),
    ]
