# Generated by Django 5.2.4 on 2025-09-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_alter_pageimage_extract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='segmentation_choice',
            field=models.CharField(choices=[('none', 'None'), ('generic', 'Generic'), ('contoured', 'Contoured')], db_index=True, default='none', max_length=16),
        ),
    ]
