# Generated by Django 5.2.4 on 2025-09-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_alter_pageimage_segmentation_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking and cancellation', max_length=255, null=True),
        ),
    ]
