# Generated by Django 5.2.4 on 2025-09-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_pageimage_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(help_text='Hex color like #RRGGBB', max_length=7)),
                ('sync_id', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workspace.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'label'], name='workspace_t_workspa_11f6e8_idx')],
                'unique_together': {('workspace', 'label')},
            },
        ),
    ]
