# Generated by Django 5.2.4 on 2025-07-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0002_pageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_id', models.PositiveIntegerField()),
                ('total_vertices', models.PositiveIntegerField()),
                ('vertices', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='workspace.pageimage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='workspace.workspace')),
            ],
        ),
    ]
