# Generated by Django 5.2.4 on 2025-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
