# Generated by Django 5.2.4 on 2025-08-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_polygon_synced_at_polygon_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='sync_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
