# Generated by Django 5.2.4 on 2025-08-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_polygon_sync_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
