# Generated by Django 5.2.4 on 2025-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_polygon_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
