# Generated by Django 5.2.4 on 2025-09-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_polygon_name'),
        ('workspace', '0016_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_tags', to='annotations.polygon')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_tags', to='workspace.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['polygon', 'tag'], name='annotations_polygon_9a7533_idx')],
                'unique_together': {('polygon', 'tag')},
            },
        ),
    ]
